// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/optim-ember/Ember.tsx": () => import("../components/mockups/optim-ember/Ember.tsx"),
  "./components/mockups/optim-meridian/Meridian.tsx": () => import("../components/mockups/optim-meridian/Meridian.tsx"),
  "./components/mockups/optim-obsidian/Obsidian.tsx": () => import("../components/mockups/optim-obsidian/Obsidian.tsx")
};
